apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: ubuntu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: ubuntu
        image: quay.io/cybozu/ubuntu:20.04
        command: ["/usr/local/bin/pause"]
